[workspace]
resolver = "2"
members = [
	"apps/server",
    "core",
    "crates/prisma-cli"
]

[workspace.dependencies]
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.9" }